[wokwi]
version = 1
elf = ".esphome/build/esphome-web-f370e8/.pioenvs/esphome-web-f370e8/firmware.elf"
firmware = ".esphome/build/esphome-web-f370e8/.pioenvs/esphome-web-f370e8/firmware.bin"

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"